#include "console.h"
#include "global.h"
#include <iostream>
#include <iomanip>
#include <sstream>

#ifdef _WIN64
#include <io.h>
#else
#include <unistd.h>
#define _isatty isatty
#define _fileno fileno
#endif

int console::update_console(std::string& message, uint64_t indexMax, uint64_t index, std::chrono::time_point<std::chrono::high_resolution_clock> start_time, int stringstream_length)
{
    std::chrono::time_point end_time = std::chrono::high_resolution_clock::now();
    double timeInSecondsFromstart_time = (0.000000001 * std::chrono::duration_cast<std::chrono::nanoseconds>(end_time - start_time).count());

    double percent = ((double)index / (double)indexMax) * 100.0;
    std::stringstream ss;
    ss << message << std::fixed << std::setprecision(1) << percent << "% Done" << " in " << timeInSecondsFromstart_time << "s, estimated completion in " << (timeInSecondsFromstart_time / (double)index) * (indexMax - index) << "s";

    percent_progress = (uint32_t)percent;

    if (ss.str().length() > stringstream_length)
    {
        stringstream_length = (int)ss.str().length();
    }

    timing_string = ss.str();

    if (_isatty(_fileno(stdout)))
    {
        LOG_NO_ENDL("\r" << ss.str() << std::string((stringstream_length - ss.str().length()), ' ') << std::flush);
    }

    return stringstream_length;
}

void console::display_usage_info()
{
    LOG("LICENSE for rpkg:");
    LOG("");
    LOG("RPKG");
    LOG("Copyright (c) 2020+, REDACTED");
    LOG("All rights reserved.");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without modification,");
    LOG("are permitted provided that the following conditions are met:");
    LOG("");
    LOG("* Redistributions of source code must retain the above copyright notice, this");
    LOG("  list of conditions and the following disclaimer.");
    LOG("");
    LOG("* Redistributions in binary form must reproduce the above copyright notice, this");
    LOG("  list of conditions and the following disclaimer in the documentation and/or");
    LOG("  other materials provided with the distribution.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND");
    LOG("ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED");
    LOG("WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE");
    LOG("DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR");
    LOG("ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES");
    LOG("(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;");
    LOG("LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON");
    LOG("ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT");
    LOG("(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS");
    LOG("SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for ww2ogg:");
    LOG("");
    LOG("Copyright (c) 2002, Xiph.org Foundation");
    LOG("Copyright (c) 2009-2016, Adam Gashlin");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without");
    LOG("modification, are permitted provided that the following conditions");
    LOG("are met:");
    LOG("");
    LOG("- Redistributions of source code must retain the above copyright");
    LOG("notice, this list of conditions and the following disclaimer.");
    LOG("");
    LOG("- Redistributions in binary form must reproduce the above copyright");
    LOG("notice, this list of conditions and the following disclaimer in the");
    LOG("documentation and/or other materials provided with the distribution.");
    LOG("");
    LOG("- Neither the name of the Xiph.org Foundation nor the names of its");
    LOG("contributors may be used to endorse or promote products derived from");
    LOG("this software without specific prior written permission.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS");
    LOG("``AS IS\'\' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT");
    LOG("LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR");
    LOG("A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION");
    LOG("OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,");
    LOG("SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT");
    LOG("LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,");
    LOG("DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY");
    LOG("THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT");
    LOG("(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE");
    LOG("OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for Costura Fody:");
    LOG("");
    LOG("The MIT License");
    LOG("");
    LOG("Copyright (c) 2012 Simon Cropp and contributors");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in");
    LOG("all copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
    LOG("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN");
    LOG("THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for json:");
    LOG("");
    LOG("MIT License ");
    LOG("");
    LOG("Copyright (c) 2013-2021 Niels Lohmann");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in all");
    LOG("copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
    LOG("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE");
    LOG("SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for lz4:");
    LOG("");
    LOG("LZ4 Library");
    LOG("Copyright (c) 2011-2020, Yann Collet");
    LOG("All rights reserved.");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without modification,");
    LOG("are permitted provided that the following conditions are met:");
    LOG("");
    LOG("* Redistributions of source code must retain the above copyright notice, this");
    LOG("  list of conditions and the following disclaimer.");
    LOG("");
    LOG("* Redistributions in binary form must reproduce the above copyright notice, this");
    LOG("  list of conditions and the following disclaimer in the documentation and/or");
    LOG("  other materials provided with the distribution.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND");
    LOG("ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED");
    LOG("WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE");
    LOG("DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR");
    LOG("ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES");
    LOG("(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;");
    LOG("LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON");
    LOG("ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT");
    LOG("(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS");
    LOG("SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for MahApps.Metro:");
    LOG("");
    LOG("MIT License");
    LOG("");
    LOG("Copyright (c) .NET Foundation and Contributors. All rights reserved.");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in all");
    LOG("copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
    LOG("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE");
    LOG("SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for ogg:");
    LOG("");
    LOG("Copyright (c) 2002, Xiph.org Foundation");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without");
    LOG("modification, are permitted provided that the following conditions");
    LOG("are met:");
    LOG("");
    LOG("- Redistributions of source code must retain the above copyright");
    LOG("notice, this list of conditions and the following disclaimer.");
    LOG("");
    LOG("- Redistributions in binary form must reproduce the above copyright");
    LOG("notice, this list of conditions and the following disclaimer in the");
    LOG("documentation and/or other materials provided with the distribution.");
    LOG("");
    LOG("- Neither the name of the Xiph.org Foundation nor the names of its");
    LOG("contributors may be used to endorse or promote products derived from");
    LOG("this software without specific prior written permission.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS");
    LOG("``AS IS\'\' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT");
    LOG("LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR");
    LOG("A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION");
    LOG("OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,");
    LOG("SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT");
    LOG("LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,");
    LOG("DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY");
    LOG("THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT");
    LOG("(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE");
    LOG("OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for Ookii Dialogs:");
    LOG("");
    LOG("BSD 3-Clause License");
    LOG("");
    LOG("Copyright (c) C. Augusto Proiete 2018-2021");
    LOG("Copyright (c) Sven Groot         2009-2018");
    LOG("All rights reserved.");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without");
    LOG("modification, are permitted provided that the following conditions are met:");
    LOG("");
    LOG("1. Redistributions of source code must retain the above copyright notice, this");
    LOG("   list of conditions and the following disclaimer.");
    LOG("");
    LOG("2. Redistributions in binary form must reproduce the above copyright notice,");
    LOG("   this list of conditions and the following disclaimer in the documentation");
    LOG("   and/or other materials provided with the distribution.");
    LOG("");
    LOG("3. Neither the name of the copyright holder nor the names of its");
    LOG("   contributors may be used to endorse or promote products derived from");
    LOG("   this software without specific prior written permission.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"");
    LOG("AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE");
    LOG("IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE");
    LOG("DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE");
    LOG("FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL");
    LOG("DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR");
    LOG("SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER");
    LOG("CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,");
    LOG("OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE");
    LOG("OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for revorb:");
    LOG("");
    LOG("REVORB - Recomputes page granule positions in Ogg Vorbis files.");
    LOG("version 0.2 (2008/06/29)");
    LOG("");
    LOG("Copyright (c) 2008, Jiri Hruska <jiri.hruska@fud.cz>");
    LOG("");
    LOG("Permission to use, copy, modify, and/or distribute this software for any");
    LOG("purpose with or without fee is hereby granted, provided that the above");
    LOG("copyright notice and this permission notice appear in all copies.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES");
    LOG("WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF");
    LOG("MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR");
    LOG("ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES");
    LOG("WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN");
    LOG("ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF");
    LOG("OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for vorbis:");
    LOG("");
    LOG("Copyright (c) 2002-2020 Xiph.org Foundation");
    LOG("");
    LOG("Redistribution and use in source and binary forms, with or without");
    LOG("modification, are permitted provided that the following conditions");
    LOG("are met:");
    LOG("");
    LOG("- Redistributions of source code must retain the above copyright");
    LOG("notice, this list of conditions and the following disclaimer.");
    LOG("");
    LOG("- Redistributions in binary form must reproduce the above copyright");
    LOG("notice, this list of conditions and the following disclaimer in the");
    LOG("documentation and/or other materials provided with the distribution.");
    LOG("");
    LOG("- Neither the name of the Xiph.org Foundation nor the names of its");
    LOG("contributors may be used to endorse or promote products derived from");
    LOG("this software without specific prior written permission.");
    LOG("");
    LOG("THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS");
    LOG("``AS IS\'\' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT");
    LOG("LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR");
    LOG("A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION");
    LOG("OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,");
    LOG("SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT");
    LOG("LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,");
    LOG("DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY");
    LOG("THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT");
    LOG("(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE");
    LOG("OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for SharpCompress:");
    LOG("");
    LOG("The MIT License (MIT)");
    LOG("");
    LOG("Copyright (c) 2014  Adam Hathcock");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in");
    LOG("all copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
    LOG("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN");
    LOG("THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for NAudio:");
    LOG("");
    LOG("Copyright 2020 Mark Heath");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in");
    LOG("all copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE ");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER ");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING");
    LOG("FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS");
    LOG("IN THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for Helix Toolkit:");
    LOG("");
    LOG("The MIT License (MIT)");
    LOG("");
    LOG("Copyright (c) 2019 Helix Toolkit contributors");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a");
    LOG("copy of this software and associated documentation files (the");
    LOG("\"Software\"), to deal in the Software without restriction, including");
    LOG("without limitation the rights to use, copy, modify, merge, publish,");
    LOG("distribute, sublicense, and/or sell copies of the Software, and to");
    LOG("permit persons to whom the Software is furnished to do so, subject to");
    LOG("the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included");
    LOG("in all copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS");
    LOG("OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF");
    LOG("MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.");
    LOG("IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY");
    LOG("CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,");
    LOG("TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE");
    LOG("SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for DirectXTex:");
    LOG("");
    LOG("The MIT License (MIT)");
    LOG("");
    LOG("Copyright (c) 2011-2021 Microsoft Corp");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy of this");
    LOG("software and associated documentation files (the \"Software\"), to deal in the Software");
    LOG("without restriction, including without limitation the rights to use, copy, modify,");
    LOG("merge, publish, distribute, sublicense, and/or sell copies of the Software, and to");
    LOG("permit persons to whom the Software is furnished to do so, subject to the following");
    LOG("conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in all copies");
    LOG("or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,");
    LOG("INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A");
    LOG("PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT");
    LOG("HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF");
    LOG("CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE");
    LOG("OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for DirectXMath:");
    LOG("");
    LOG("The MIT License (MIT)");
    LOG("");
    LOG("Copyright (c) 2011-2021 Microsoft Corp");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy of this");
    LOG("software and associated documentation files (the \"Software\"), to deal in the Software");
    LOG("without restriction, including without limitation the rights to use, copy, modify,");
    LOG("merge, publish, distribute, sublicense, and/or sell copies of the Software, and to");
    LOG("permit persons to whom the Software is furnished to do so, subject to the following");
    LOG("conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in all copies");
    LOG("or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,");
    LOG("INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A");
    LOG("PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT");
    LOG("HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF");
    LOG("CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE");
    LOG("OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for glTF-SDK:");
    LOG("");
    LOG("MIT License");
    LOG("");
    LOG("Copyright (c) Microsoft Corporation. All rights reserved.");
    LOG("");
    LOG("Permission is hereby granted, free of charge, to any person obtaining a copy");
    LOG("of this software and associated documentation files (the \"Software\"), to deal");
    LOG("in the Software without restriction, including without limitation the rights");
    LOG("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
    LOG("copies of the Software, and to permit persons to whom the Software is");
    LOG("furnished to do so, subject to the following conditions:");
    LOG("");
    LOG("The above copyright notice and this permission notice shall be included in all");
    LOG("copies or substantial portions of the Software.");
    LOG("");
    LOG("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
    LOG("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
    LOG("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
    LOG("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
    LOG("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
    LOG("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE");
    LOG("SOFTWARE");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for mikktspace:");
    LOG("");
    LOG("Copyright (C) 2011 by Morten S. Mikkelsen");
    LOG("");
    LOG("This software is provided 'as-is', without any express or implied");
    LOG("warranty.  In no event will the authors be held liable for any damages");
    LOG("arising from the use of this software.");
    LOG("");
    LOG("Permission is granted to anyone to use this software for any purpose,");
    LOG("including commercial applications, and to alter it and redistribute it");
    LOG("freely, subject to the following restrictions:");
    LOG("");
    LOG("1. The origin of this software must not be misrepresented; you must not");
    LOG("   claim that you wrote the original software. If you use this software");
    LOG("   in a product, an acknowledgment in the product documentation would be");
    LOG("   appreciated but is not required.");
    LOG("2. Altered source versions must be plainly marked as such, and must not be");
    LOG("   misrepresented as being the original software.");
    LOG("3. This notice may not be removed or altered from any source distribution.");
    LOG("");
    LOG("");
    LOG("");
    LOG("LICENSE for ResourceTool (DLL):");
    LOG("");
    LOG("(We were given permission by the author to utilize ResourceTool 'as a DLL'");
    LOG("and that even though ResourceTool is GPL-3 that we could retain our MIT License.)");
    LOG("");
    LOG("Copyright Orfeas Zafeiris");
    LOG("");
    LOG("                    GNU GENERAL PUBLIC LICENSE");
    LOG("                       Version 3, 29 June 2007");
    LOG("");
    LOG(" Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>");
    LOG(" Everyone is permitted to copy and distribute verbatim copies");
    LOG(" of this license document, but changing it is not allowed.");
    LOG("");
    LOG("                            Preamble");
    LOG("");
    LOG("  The GNU General Public License is a free, copyleft license for");
    LOG("software and other kinds of works.");
    LOG("");
    LOG("  The licenses for most software and other practical works are designed");
    LOG("to take away your freedom to share and change the works.  By contrast,");
    LOG("the GNU General Public License is intended to guarantee your freedom to");
    LOG("share and change all versions of a program--to make sure it remains free");
    LOG("software for all its users.  We, the Free Software Foundation, use the");
    LOG("GNU General Public License for most of our software; it applies also to");
    LOG("any other work released this way by its authors.  You can apply it to");
    LOG("your programs, too.");
    LOG("");
    LOG("  When we speak of free software, we are referring to freedom, not");
    LOG("price.  Our General Public Licenses are designed to make sure that you");
    LOG("have the freedom to distribute copies of free software (and charge for");
    LOG("them if you wish), that you receive source code or can get it if you");
    LOG("want it, that you can change the software or use pieces of it in new");
    LOG("free programs, and that you know you can do these things.");
    LOG("");
    LOG("  To protect your rights, we need to prevent others from denying you");
    LOG("these rights or asking you to surrender the rights.  Therefore, you have");
    LOG("certain responsibilities if you distribute copies of the software, or if");
    LOG("you modify it: responsibilities to respect the freedom of others.");
    LOG("");
    LOG("  For example, if you distribute copies of such a program, whether");
    LOG("gratis or for a fee, you must pass on to the recipients the same");
    LOG("freedoms that you received.  You must make sure that they, too, receive");
    LOG("or can get the source code.  And you must show them these terms so they");
    LOG("know their rights.");
    LOG("");
    LOG("  Developers that use the GNU GPL protect your rights with two steps:");
    LOG("(1) assert copyright on the software, and (2) offer you this License");
    LOG("giving you legal permission to copy, distribute and/or modify it.");
    LOG("");
    LOG("  For the developers' and authors' protection, the GPL clearly explains");
    LOG("that there is no warranty for this free software.  For both users' and");
    LOG("authors' sake, the GPL requires that modified versions be marked as");
    LOG("changed, so that their problems will not be attributed erroneously to");
    LOG("authors of previous versions.");
    LOG("");
    LOG("  Some devices are designed to deny users access to install or run");
    LOG("modified versions of the software inside them, although the manufacturer");
    LOG("can do so.  This is fundamentally incompatible with the aim of");
    LOG("protecting users' freedom to change the software.  The systematic");
    LOG("pattern of such abuse occurs in the area of products for individuals to");
    LOG("use, which is precisely where it is most unacceptable.  Therefore, we");
    LOG("have designed this version of the GPL to prohibit the practice for those");
    LOG("products.  If such problems arise substantially in other domains, we");
    LOG("stand ready to extend this provision to those domains in future versions");
    LOG("of the GPL, as needed to protect the freedom of users.");
    LOG("");
    LOG("  Finally, every program is threatened constantly by software patents.");
    LOG("States should not allow patents to restrict development and use of");
    LOG("software on general-purpose computers, but in those that do, we wish to");
    LOG("avoid the special danger that patents applied to a free program could");
    LOG("make it effectively proprietary.  To prevent this, the GPL assures that");
    LOG("patents cannot be used to render the program non-free.");
    LOG("");
    LOG("  The precise terms and conditions for copying, distribution and");
    LOG("modification follow.");
    LOG("");
    LOG("                       TERMS AND CONDITIONS");
    LOG("");
    LOG("  0. Definitions.");
    LOG("");
    LOG("  \"This License\" refers to version 3 of the GNU General Public License.");
    LOG("");
    LOG("  \Copyright\" also means copyright-like laws that apply to other kinds of");
    LOG("works, such as semiconductor masks.");
    LOG("");
    LOG("  \"The Program\" refers to any copyrightable work licensed under this");
    LOG("License.  Each licensee is addressed as \"you\".  \"Licensees\" and");
    LOG("\"recipients\" may be individuals or organizations.");
    LOG("");
    LOG("  To \"modify\" a work means to copy from or adapt all or part of the work");
    LOG("in a fashion requiring copyright permission, other than the making of an");
    LOG("exact copy.  The resulting work is called a \"modified version\" of the");
    LOG("earlier work or a work \"based on\" the earlier work.");
    LOG("");
    LOG("  A \"covered work\" means either the unmodified Program or a work based");
    LOG("on the Program.");
    LOG("");
    LOG("  To \"propagate\" a work means to do anything with it that, without");
    LOG("permission, would make you directly or secondarily liable for");
    LOG("infringement under applicable copyright law, except executing it on a");
    LOG("computer or modifying a private copy.  Propagation includes copying,");
    LOG("distribution (with or without modification), making available to the");
    LOG("public, and in some countries other activities as well.");
    LOG("");
    LOG("  To \"convey\" a work means any kind of propagation that enables other");
    LOG("parties to make or receive copies.  Mere interaction with a user through");
    LOG("a computer network, with no transfer of a copy, is not conveying.");
    LOG("");
    LOG("  An interactive user interface displays \"Appropriate Legal Notices\"");
    LOG("to the extent that it includes a convenient and prominently visible");
    LOG("feature that (1) displays an appropriate copyright notice, and (2)");
    LOG("tells the user that there is no warranty for the work (except to the");
    LOG("extent that warranties are provided), that licensees may convey the");
    LOG("work under this License, and how to view a copy of this License.  If");
    LOG("the interface presents a list of user commands or options, such as a");
    LOG("menu, a prominent item in the list meets this criterion.");
    LOG("");
    LOG("  1. Source Code.");
    LOG("");
    LOG("  The \"source code\" for a work means the preferred form of the work");
    LOG("for making modifications to it.  \"Object code\" means any non-source");
    LOG("form of a work.");
    LOG("");
    LOG("  A \"Standard Interface\" means an interface that either is an official");
    LOG("standard defined by a recognized standards body, or, in the case of");
    LOG("interfaces specified for a particular programming language, one that");
    LOG("is widely used among developers working in that language.");
    LOG("");
    LOG("  The \"System Libraries\" of an executable work include anything, other");
    LOG("than the work as a whole, that (a) is included in the normal form of");
    LOG("packaging a Major Component, but which is not part of that Major");
    LOG("Component, and (b) serves only to enable use of the work with that");
    LOG("Major Component, or to implement a Standard Interface for which an");
    LOG("implementation is available to the public in source code form.  A");
    LOG("\"Major Component\", in this context, means a major essential component");
    LOG("(kernel, window system, and so on) of the specific operating system");
    LOG("(if any) on which the executable work runs, or a compiler used to");
    LOG("produce the work, or an object code interpreter used to run it.");
    LOG("");
    LOG("  The \"Corresponding Source\" for a work in object code form means all");
    LOG("the source code needed to generate, install, and (for an executable");
    LOG("work) run the object code and to modify the work, including scripts to");
    LOG("control those activities.  However, it does not include the work's");
    LOG("System Libraries, or general-purpose tools or generally available free");
    LOG("programs which are used unmodified in performing those activities but");
    LOG("which are not part of the work.  For example, Corresponding Source");
    LOG("includes interface definition files associated with source files for");
    LOG("the work, and the source code for shared libraries and dynamically");
    LOG("linked subprograms that the work is specifically designed to require,");
    LOG("such as by intimate data communication or control flow between those");
    LOG("subprograms and other parts of the work.");
    LOG("");
    LOG("  The Corresponding Source need not include anything that users");
    LOG("can regenerate automatically from other parts of the Corresponding");
    LOG("Source.");
    LOG("");
    LOG("  The Corresponding Source for a work in source code form is that");
    LOG("same work.");
    LOG("");
    LOG("  2. Basic Permissions.");
    LOG("");
    LOG("  All rights granted under this License are granted for the term of");
    LOG("copyright on the Program, and are irrevocable provided the stated");
    LOG("conditions are met.  This License explicitly affirms your unlimited");
    LOG("permission to run the unmodified Program.  The output from running a");
    LOG("covered work is covered by this License only if the output, given its");
    LOG("content, constitutes a covered work.  This License acknowledges your");
    LOG("rights of fair use or other equivalent, as provided by copyright law.");
    LOG("");
    LOG("  You may make, run and propagate covered works that you do not");
    LOG("convey, without conditions so long as your license otherwise remains");
    LOG("in force.  You may convey covered works to others for the sole purpose");
    LOG("of having them make modifications exclusively for you, or provide you");
    LOG("with facilities for running those works, provided that you comply with");
    LOG("the terms of this License in conveying all material for which you do");
    LOG("not control copyright.  Those thus making or running the covered works");
    LOG("for you must do so exclusively on your behalf, under your direction");
    LOG("and control, on terms that prohibit them from making any copies of");
    LOG("your copyrighted material outside their relationship with you.");
    LOG("");
    LOG("  Conveying under any other circumstances is permitted solely under");
    LOG("the conditions stated below.  Sublicensing is not allowed; section 10");
    LOG("makes it unnecessary.");
    LOG("");
    LOG("  3. Protecting Users' Legal Rights From Anti-Circumvention Law.");
    LOG("");
    LOG("  No covered work shall be deemed part of an effective technological");
    LOG("measure under any applicable law fulfilling obligations under article");
    LOG("11 of the WIPO copyright treaty adopted on 20 December 1996, or");
    LOG("similar laws prohibiting or restricting circumvention of such");
    LOG("measures.");
    LOG("");
    LOG("  When you convey a covered work, you waive any legal power to forbid");
    LOG("circumvention of technological measures to the extent such circumvention");
    LOG("is effected by exercising rights under this License with respect to");
    LOG("the covered work, and you disclaim any intention to limit operation or");
    LOG("modification of the work as a means of enforcing, against the work's");
    LOG("users, your or third parties' legal rights to forbid circumvention of");
    LOG("technological measures.");
    LOG("");
    LOG("  4. Conveying Verbatim Copies.");
    LOG("");
    LOG("  You may convey verbatim copies of the Program's source code as you");
    LOG("receive it, in any medium, provided that you conspicuously and");
    LOG("appropriately publish on each copy an appropriate copyright notice;");
    LOG("keep intact all notices stating that this License and any");
    LOG("non-permissive terms added in accord with section 7 apply to the code;");
    LOG("keep intact all notices of the absence of any warranty; and give all");
    LOG("recipients a copy of this License along with the Program.");
    LOG("");
    LOG("  You may charge any price or no price for each copy that you convey,");
    LOG("and you may offer support or warranty protection for a fee.");
    LOG("");
    LOG("  5. Conveying Modified Source Versions.");
    LOG("");
    LOG("  You may convey a work based on the Program, or the modifications to");
    LOG("produce it from the Program, in the form of source code under the");
    LOG("terms of section 4, provided that you also meet all of these conditions:");
    LOG("");
    LOG("    a) The work must carry prominent notices stating that you modified");
    LOG("    it, and giving a relevant date.");
    LOG("");
    LOG("    b) The work must carry prominent notices stating that it is");
    LOG("    released under this License and any conditions added under section");
    LOG("    7.  This requirement modifies the requirement in section 4 to");
    LOG("    \"keep intact all notices\".");
    LOG("");
    LOG("    c) You must license the entire work, as a whole, under this");
    LOG("    License to anyone who comes into possession of a copy.  This");
    LOG("    License will therefore apply, along with any applicable section 7");
    LOG("    additional terms, to the whole of the work, and all its parts,");
    LOG("    regardless of how they are packaged.  This License gives no");
    LOG("    permission to license the work in any other way, but it does not");
    LOG("    invalidate such permission if you have separately received it.");
    LOG("");
    LOG("    d) If the work has interactive user interfaces, each must display");
    LOG("    Appropriate Legal Notices; however, if the Program has interactive");
    LOG("    interfaces that do not display Appropriate Legal Notices, your");
    LOG("    work need not make them do so.");
    LOG("");
    LOG("  A compilation of a covered work with other separate and independent");
    LOG("works, which are not by their nature extensions of the covered work,");
    LOG("and which are not combined with it such as to form a larger program,");
    LOG("in or on a volume of a storage or distribution medium, is called an");
    LOG("\"aggregate\" if the compilation and its resulting copyright are not");
    LOG("used to limit the access or legal rights of the compilation's users");
    LOG("beyond what the individual works permit.  Inclusion of a covered work");
    LOG("in an aggregate does not cause this License to apply to the other");
    LOG("parts of the aggregate.");
    LOG("");
    LOG("  6. Conveying Non-Source Forms.");
    LOG("");
    LOG("  You may convey a covered work in object code form under the terms");
    LOG("of sections 4 and 5, provided that you also convey the");
    LOG("machine-readable Corresponding Source under the terms of this License,");
    LOG("in one of these ways:");
    LOG("");
    LOG("    a) Convey the object code in, or embodied in, a physical product");
    LOG("    (including a physical distribution medium), accompanied by the");
    LOG("    Corresponding Source fixed on a durable physical medium");
    LOG("    customarily used for software interchange.");
    LOG("");
    LOG("    b) Convey the object code in, or embodied in, a physical product");
    LOG("    (including a physical distribution medium), accompanied by a");
    LOG("    written offer, valid for at least three years and valid for as");
    LOG("    long as you offer spare parts or customer support for that product");
    LOG("    model, to give anyone who possesses the object code either (1) a");
    LOG("    copy of the Corresponding Source for all the software in the");
    LOG("    product that is covered by this License, on a durable physical");
    LOG("    medium customarily used for software interchange, for a price no");
    LOG("    more than your reasonable cost of physically performing this");
    LOG("    conveying of source, or (2) access to copy the");
    LOG("    Corresponding Source from a network server at no charge.");
    LOG("");
    LOG("    c) Convey individual copies of the object code with a copy of the");
    LOG("    written offer to provide the Corresponding Source.  This");
    LOG("    alternative is allowed only occasionally and noncommercially, and");
    LOG("    only if you received the object code with such an offer, in accord");
    LOG("    with subsection 6b.");
    LOG("");
    LOG("    d) Convey the object code by offering access from a designated");
    LOG("    place (gratis or for a charge), and offer equivalent access to the");
    LOG("    Corresponding Source in the same way through the same place at no");
    LOG("    further charge.  You need not require recipients to copy the");
    LOG("    Corresponding Source along with the object code.  If the place to");
    LOG("    copy the object code is a network server, the Corresponding Source");
    LOG("    may be on a different server (operated by you or a third party)");
    LOG("    that supports equivalent copying facilities, provided you maintain");
    LOG("    clear directions next to the object code saying where to find the");
    LOG("    Corresponding Source.  Regardless of what server hosts the");
    LOG("    Corresponding Source, you remain obligated to ensure that it is");
    LOG("    available for as long as needed to satisfy these requirements.");
    LOG("");
    LOG("    e) Convey the object code using peer-to-peer transmission, provided");
    LOG("    you inform other peers where the object code and Corresponding");
    LOG("    Source of the work are being offered to the general public at no");
    LOG("    charge under subsection 6d.");
    LOG("");
    LOG("  A separable portion of the object code, whose source code is excluded");
    LOG("from the Corresponding Source as a System Library, need not be");
    LOG("included in conveying the object code work.");
    LOG("");
    LOG("  A \"User Product\" is either (1) a \"consumer product\", which means any");
    LOG("tangible personal property which is normally used for personal, family,");
    LOG("or household purposes, or (2) anything designed or sold for incorporation");
    LOG("into a dwelling.  In determining whether a product is a consumer product,");
    LOG("doubtful cases shall be resolved in favor of coverage.  For a particular");
    LOG("product received by a particular user, \"normally used\" refers to a");
    LOG("typical or common use of that class of product, regardless of the status");
    LOG("of the particular user or of the way in which the particular user");
    LOG("actually uses, or expects or is expected to use, the product.  A product");
    LOG("is a consumer product regardless of whether the product has substantial");
    LOG("commercial, industrial or non-consumer uses, unless such uses represent");
    LOG("the only significant mode of use of the product.");
    LOG("");
    LOG("  \"Installation Information\" for a User Product means any methods,");
    LOG("procedures, authorization keys, or other information required to install");
    LOG("and execute modified versions of a covered work in that User Product from");
    LOG("a modified version of its Corresponding Source.  The information must");
    LOG("suffice to ensure that the continued functioning of the modified object");
    LOG("code is in no case prevented or interfered with solely because");
    LOG("modification has been made.");
    LOG("");
    LOG("  If you convey an object code work under this section in, or with, or");
    LOG("specifically for use in, a User Product, and the conveying occurs as");
    LOG("part of a transaction in which the right of possession and use of the");
    LOG("User Product is transferred to the recipient in perpetuity or for a");
    LOG("fixed term (regardless of how the transaction is characterized), the");
    LOG("Corresponding Source conveyed under this section must be accompanied");
    LOG("by the Installation Information.  But this requirement does not apply");
    LOG("if neither you nor any third party retains the ability to install");
    LOG("modified object code on the User Product (for example, the work has");
    LOG("been installed in ROM).");
    LOG("");
    LOG("  The requirement to provide Installation Information does not include a");
    LOG("requirement to continue to provide support service, warranty, or updates");
    LOG("for a work that has been modified or installed by the recipient, or for");
    LOG("the User Product in which it has been modified or installed.  Access to a");
    LOG("network may be denied when the modification itself materially and");
    LOG("adversely affects the operation of the network or violates the rules and");
    LOG("protocols for communication across the network.");
    LOG("");
    LOG("  Corresponding Source conveyed, and Installation Information provided,");
    LOG("in accord with this section must be in a format that is publicly");
    LOG("documented (and with an implementation available to the public in");
    LOG("source code form), and must require no special password or key for");
    LOG("unpacking, reading or copying.");
    LOG("");
    LOG("  7. Additional Terms.");
    LOG("");
    LOG("  \"Additional permissions\" are terms that supplement the terms of this");
    LOG("License by making exceptions from one or more of its conditions.");
    LOG("Additional permissions that are applicable to the entire Program shall");
    LOG("be treated as though they were included in this License, to the extent");
    LOG("that they are valid under applicable law.  If additional permissions");
    LOG("apply only to part of the Program, that part may be used separately");
    LOG("under those permissions, but the entire Program remains governed by");
    LOG("this License without regard to the additional permissions.");
    LOG("");
    LOG("  When you convey a copy of a covered work, you may at your option");
    LOG("remove any additional permissions from that copy, or from any part of");
    LOG("it.  (Additional permissions may be written to require their own");
    LOG("removal in certain cases when you modify the work.)  You may place");
    LOG("additional permissions on material, added by you to a covered work,");
    LOG("for which you have or can give appropriate copyright permission.");
    LOG("");
    LOG("  Notwithstanding any other provision of this License, for material you");
    LOG("add to a covered work, you may (if authorized by the copyright holders of");
    LOG("that material) supplement the terms of this License with terms:");
    LOG("");
    LOG("    a) Disclaiming warranty or limiting liability differently from the");
    LOG("    terms of sections 15 and 16 of this License; or");
    LOG("");
    LOG("    b) Requiring preservation of specified reasonable legal notices or");
    LOG("    author attributions in that material or in the Appropriate Legal");
    LOG("    Notices displayed by works containing it; or");
    LOG("");
    LOG("    c) Prohibiting misrepresentation of the origin of that material, or");
    LOG("    requiring that modified versions of such material be marked in");
    LOG("    reasonable ways as different from the original version; or");
    LOG("");
    LOG("    d) Limiting the use for publicity purposes of names of licensors or");
    LOG("    authors of the material; or");
    LOG("");
    LOG("    e) Declining to grant rights under trademark law for use of some");
    LOG("    trade names, trademarks, or service marks; or");
    LOG("");
    LOG("    f) Requiring indemnification of licensors and authors of that");
    LOG("    material by anyone who conveys the material (or modified versions of");
    LOG("    it) with contractual assumptions of liability to the recipient, for");
    LOG("    any liability that these contractual assumptions directly impose on");
    LOG("    those licensors and authors.");
    LOG("");
    LOG("  All other non-permissive additional terms are considered \"further");
    LOG("restrictions\" within the meaning of section 10.  If the Program as you");
    LOG("received it, or any part of it, contains a notice stating that it is");
    LOG("governed by this License along with a term that is a further");
    LOG("restriction, you may remove that term.  If a license document contains");
    LOG("a further restriction but permits relicensing or conveying under this");
    LOG("License, you may add to a covered work material governed by the terms");
    LOG("of that license document, provided that the further restriction does");
    LOG("not survive such relicensing or conveying.");
    LOG("");
    LOG("  If you add terms to a covered work in accord with this section, you");
    LOG("must place, in the relevant source files, a statement of the");
    LOG("additional terms that apply to those files, or a notice indicating");
    LOG("where to find the applicable terms.");
    LOG("");
    LOG("  Additional terms, permissive or non-permissive, may be stated in the");
    LOG("form of a separately written license, or stated as exceptions;");
    LOG("the above requirements apply either way.");
    LOG("");
    LOG("  8. Termination.");
    LOG("");
    LOG("  You may not propagate or modify a covered work except as expressly");
    LOG("provided under this License.  Any attempt otherwise to propagate or");
    LOG("modify it is void, and will automatically terminate your rights under");
    LOG("this License (including any patent licenses granted under the third");
    LOG("paragraph of section 11).");
    LOG("");
    LOG("  However, if you cease all violation of this License, then your");
    LOG("license from a particular copyright holder is reinstated (a)");
    LOG("provisionally, unless and until the copyright holder explicitly and");
    LOG("finally terminates your license, and (b) permanently, if the copyright");
    LOG("holder fails to notify you of the violation by some reasonable means");
    LOG("prior to 60 days after the cessation.");
    LOG("");
    LOG("  Moreover, your license from a particular copyright holder is");
    LOG("reinstated permanently if the copyright holder notifies you of the");
    LOG("violation by some reasonable means, this is the first time you have");
    LOG("received notice of violation of this License (for any work) from that");
    LOG("copyright holder, and you cure the violation prior to 30 days after");
    LOG("your receipt of the notice.");
    LOG("");
    LOG("  Termination of your rights under this section does not terminate the");
    LOG("licenses of parties who have received copies or rights from you under");
    LOG("this License.  If your rights have been terminated and not permanently");
    LOG("reinstated, you do not qualify to receive new licenses for the same");
    LOG("material under section 10.");
    LOG("");
    LOG("  9. Acceptance Not Required for Having Copies.");
    LOG("");
    LOG("  You are not required to accept this License in order to receive or");
    LOG("run a copy of the Program.  Ancillary propagation of a covered work");
    LOG("occurring solely as a consequence of using peer-to-peer transmission");
    LOG("to receive a copy likewise does not require acceptance.  However,");
    LOG("nothing other than this License grants you permission to propagate or");
    LOG("modify any covered work.  These actions infringe copyright if you do");
    LOG("not accept this License.  Therefore, by modifying or propagating a");
    LOG("covered work, you indicate your acceptance of this License to do so.");
    LOG("");
    LOG("  10. Automatic Licensing of Downstream Recipients.");
    LOG("");
    LOG("  Each time you convey a covered work, the recipient automatically");
    LOG("receives a license from the original licensors, to run, modify and");
    LOG("propagate that work, subject to this License.  You are not responsible");
    LOG("for enforcing compliance by third parties with this License.");
    LOG("");
    LOG("  An \"entity transaction\" is a transaction transferring control of an");
    LOG("organization, or substantially all assets of one, or subdividing an");
    LOG("organization, or merging organizations.  If propagation of a covered");
    LOG("work results from an entity transaction, each party to that");
    LOG("transaction who receives a copy of the work also receives whatever");
    LOG("licenses to the work the party's predecessor in interest had or could");
    LOG("give under the previous paragraph, plus a right to possession of the");
    LOG("Corresponding Source of the work from the predecessor in interest, if");
    LOG("the predecessor has it or can get it with reasonable efforts.");
    LOG("");
    LOG("  You may not impose any further restrictions on the exercise of the");
    LOG("rights granted or affirmed under this License.  For example, you may");
    LOG("not impose a license fee, royalty, or other charge for exercise of");
    LOG("rights granted under this License, and you may not initiate litigation");
    LOG("(including a cross-claim or counterclaim in a lawsuit) alleging that");
    LOG("any patent claim is infringed by making, using, selling, offering for");
    LOG("sale, or importing the Program or any portion of it.");
    LOG("");
    LOG("  11. Patents.");
    LOG("");
    LOG("  A \"contributor\" is a copyright holder who authorizes use under this");
    LOG("License of the Program or a work on which the Program is based.  The");
    LOG("work thus licensed is called the contributor's \"contributor version\".");
    LOG("");
    LOG("  A contributor's \"essential patent claims\" are all patent claims");
    LOG("owned or controlled by the contributor, whether already acquired or");
    LOG("hereafter acquired, that would be infringed by some manner, permitted");
    LOG("by this License, of making, using, or selling its contributor version,");
    LOG("but do not include claims that would be infringed only as a");
    LOG("consequence of further modification of the contributor version.  For");
    LOG("purposes of this definition, \"control\" includes the right to grant");
    LOG("patent sublicenses in a manner consistent with the requirements of");
    LOG("this License.");
    LOG("");
    LOG("  Each contributor grants you a non-exclusive, worldwide, royalty-free");
    LOG("patent license under the contributor's essential patent claims, to");
    LOG("make, use, sell, offer for sale, import and otherwise run, modify and");
    LOG("propagate the contents of its contributor version.");
    LOG("");
    LOG("  In the following three paragraphs, a \"patent license\" is any express");
    LOG("agreement or commitment, however denominated, not to enforce a patent");
    LOG("(such as an express permission to practice a patent or covenant not to");
    LOG("sue for patent infringement).  To \"grant\" such a patent license to a");
    LOG("party means to make such an agreement or commitment not to enforce a");
    LOG("patent against the party.");
    LOG("");
    LOG("  If you convey a covered work, knowingly relying on a patent license,");
    LOG("and the Corresponding Source of the work is not available for anyone");
    LOG("to copy, free of charge and under the terms of this License, through a");
    LOG("publicly available network server or other readily accessible means,");
    LOG("then you must either (1) cause the Corresponding Source to be so");
    LOG("available, or (2) arrange to deprive yourself of the benefit of the");
    LOG("patent license for this particular work, or (3) arrange, in a manner");
    LOG("consistent with the requirements of this License, to extend the patent");
    LOG("license to downstream recipients.  \"Knowingly relying\" means you have");
    LOG("actual knowledge that, but for the patent license, your conveying the");
    LOG("covered work in a country, or your recipient's use of the covered work");
    LOG("in a country, would infringe one or more identifiable patents in that");
    LOG("country that you have reason to believe are valid.");
    LOG("");
    LOG("  If, pursuant to or in connection with a single transaction or");
    LOG("arrangement, you convey, or propagate by procuring conveyance of, a");
    LOG("covered work, and grant a patent license to some of the parties");
    LOG("receiving the covered work authorizing them to use, propagate, modify");
    LOG("or convey a specific copy of the covered work, then the patent license");
    LOG("you grant is automatically extended to all recipients of the covered");
    LOG("work and works based on it.");
    LOG("");
    LOG("  A patent license is \"discriminatory\" if it does not include within");
    LOG("the scope of its coverage, prohibits the exercise of, or is");
    LOG("conditioned on the non-exercise of one or more of the rights that are");
    LOG("specifically granted under this License.  You may not convey a covered");
    LOG("work if you are a party to an arrangement with a third party that is");
    LOG("in the business of distributing software, under which you make payment");
    LOG("to the third party based on the extent of your activity of conveying");
    LOG("the work, and under which the third party grants, to any of the");
    LOG("parties who would receive the covered work from you, a discriminatory");
    LOG("patent license (a) in connection with copies of the covered work");
    LOG("conveyed by you (or copies made from those copies), or (b) primarily");
    LOG("for and in connection with specific products or compilations that");
    LOG("contain the covered work, unless you entered into that arrangement,");
    LOG("or that patent license was granted, prior to 28 March 2007.");
    LOG("");
    LOG("  Nothing in this License shall be construed as excluding or limiting");
    LOG("any implied license or other defenses to infringement that may");
    LOG("otherwise be available to you under applicable patent law.");
    LOG("");
    LOG("  12. No Surrender of Others' Freedom.");
    LOG("");
    LOG("  If conditions are imposed on you (whether by court order, agreement or");
    LOG("otherwise) that contradict the conditions of this License, they do not");
    LOG("excuse you from the conditions of this License.  If you cannot convey a");
    LOG("covered work so as to satisfy simultaneously your obligations under this");
    LOG("License and any other pertinent obligations, then as a consequence you may");
    LOG("not convey it at all.  For example, if you agree to terms that obligate you");
    LOG("to collect a royalty for further conveying from those to whom you convey");
    LOG("the Program, the only way you could satisfy both those terms and this");
    LOG("License would be to refrain entirely from conveying the Program.");
    LOG("");
    LOG("  13. Use with the GNU Affero General Public License.");
    LOG("");
    LOG("  Notwithstanding any other provision of this License, you have");
    LOG("permission to link or combine any covered work with a work licensed");
    LOG("under version 3 of the GNU Affero General Public License into a single");
    LOG("combined work, and to convey the resulting work.  The terms of this");
    LOG("License will continue to apply to the part which is the covered work,");
    LOG("but the special requirements of the GNU Affero General Public License,");
    LOG("section 13, concerning interaction through a network will apply to the");
    LOG("combination as such.");
    LOG("");
    LOG("  14. Revised Versions of this License.");
    LOG("");
    LOG("  The Free Software Foundation may publish revised and/or new versions of");
    LOG("the GNU General Public License from time to time.  Such new versions will");
    LOG("be similar in spirit to the present version, but may differ in detail to");
    LOG("address new problems or concerns.");
    LOG("");
    LOG("  Each version is given a distinguishing version number.  If the");
    LOG("Program specifies that a certain numbered version of the GNU General");
    LOG("Public License \" or any later version\" applies to it, you have the");
    LOG("option of following the terms and conditions either of that numbered");
    LOG("version or of any later version published by the Free Software");
    LOG("Foundation.  If the Program does not specify a version number of the");
    LOG("GNU General Public License, you may choose any version ever published");
    LOG("by the Free Software Foundation.");
    LOG("");
    LOG("  If the Program specifies that a proxy can decide which future");
    LOG("versions of the GNU General Public License can be used, that proxy's");
    LOG("public statement of acceptance of a version permanently authorizes you");
    LOG("to choose that version for the Program.");
    LOG("");
    LOG("  Later license versions may give you additional or different");
    LOG("permissions.  However, no additional obligations are imposed on any");
    LOG("author or copyright holder as a result of your choosing to follow a");
    LOG("later version.");
    LOG("");
    LOG("  15. Disclaimer of Warranty.");
    LOG("");
    LOG("  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY");
    LOG("APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT");
    LOG("HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY");
    LOG("OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,");
    LOG("THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR");
    LOG("PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM");
    LOG("IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF");
    LOG("ALL NECESSARY SERVICING, REPAIR OR CORRECTION.");
    LOG("");
    LOG("  16. Limitation of Liability.");
    LOG("");
    LOG("  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING");
    LOG("WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS");
    LOG("THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY");
    LOG("GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE");
    LOG("USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF");
    LOG("DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD");
    LOG("PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),");
    LOG("EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF");
    LOG("SUCH DAMAGES.");
    LOG("");
    LOG("  17. Interpretation of Sections 15 and 16.");
    LOG("");
    LOG("  If the disclaimer of warranty and limitation of liability provided");
    LOG("above cannot be given local legal effect according to their terms,");
    LOG("reviewing courts shall apply local law that most closely approximates");
    LOG("an absolute waiver of all civil liability in connection with the");
    LOG("Program, unless a warranty or assumption of liability accompanies a");
    LOG("copy of the Program in return for a fee.");
    LOG("");
    LOG("                     END OF TERMS AND CONDITIONS");
    LOG("");
    LOG("            How to Apply These Terms to Your New Programs");
    LOG("");
    LOG("  If you develop a new program, and you want it to be of the greatest");
    LOG("possible use to the public, the best way to achieve this is to make it");
    LOG("free software which everyone can redistribute and change under these terms.");
    LOG("");
    LOG("  To do so, attach the following notices to the program.  It is safest");
    LOG("to attach them to the start of each source file to most effectively");
    LOG("state the exclusion of warranty; and each file should have at least");
    LOG("the \"copyright\" line and a pointer to where the full notice is found.");
    LOG("");
    LOG("    <one line to give the program's name and a brief idea of what it does.>");
    LOG("    Copyright (C) <year>  <name of author>");
    LOG("");
    LOG("    This program is free software: you can redistribute it and/or modify");
    LOG("    it under the terms of the GNU General Public License as published by");
    LOG("    the Free Software Foundation, either version 3 of the License, or");
    LOG("    (at your option) any later version.");
    LOG("");
    LOG("    This program is distributed in the hope that it will be useful,");
    LOG("    but WITHOUT ANY WARRANTY; without even the implied warranty of");
    LOG("    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the");
    LOG("    GNU General Public License for more details.");
    LOG("");
    LOG("    You should have received a copy of the GNU General Public License");
    LOG("    along with this program.  If not, see <https://www.gnu.org/licenses/>.");
    LOG("");
    LOG("Also add information on how to contact you by electronic and paper mail.");
    LOG("");
    LOG("  If the program does terminal interaction, make it output a short");
    LOG("notice like this when it starts in an interactive mode:");
    LOG("");
    LOG("    <program>  Copyright (C) <year>  <name of author>");
    LOG("    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.");
    LOG("    This is free software, and you are welcome to redistribute it");
    LOG("    under certain conditions; type `show c' for details.");
    LOG("");
    LOG("The hypothetical commands `show w' and `show c' should show the appropriate");
    LOG("parts of the General Public License.  Of course, your program's commands");
    LOG("might be different; for a GUI interface, you would use an \"about box\".");
    LOG("");
    LOG("  You should also get your employer (if you work as a programmer) or school,");
    LOG("if any, to sign a \"copyright disclaimer\" for the program, if necessary.");
    LOG("For more information on this, and how to apply and follow the GNU GPL, see");
    LOG("<https://www.gnu.org/licenses/>.");
    LOG("");
    LOG("  The GNU General Public License does not permit incorporating your program");
    LOG("into proprietary programs.  If your program is a subroutine library, you");
    LOG("may consider it more useful to permit linking proprietary applications with");
    LOG("the library.  If this is what you want to do, use the GNU Lesser General");
    LOG("Public License instead of this License.  But first, please read");
    LOG("<https://www.gnu.org/licenses/why-not-lgpl.html>.");
    LOG("");
    LOG("");
    LOG("");
    LOG("rpkg-cli v2.15 - Works with RPKGv1 (GKPR) and RPKGv2 (2KPR) files.");
    LOG("--------------------------------------------------------------------------------");
    LOG("Note: All the information used to build this program was gleaned");
    LOG("      in a completely 'clean room' environment.");
    LOG("--------------------------------------------------------------------------------");
    LOG("Usage:" << std::endl);
    LOG("  Interactive Mode:");
    LOG("    - RPKG can be used in interactive mode by running:");
    LOG("        rpkg-cli.exe -i");
    LOG("    - Interactive mode lets you execute endless CLI commands in succession by way of");
    LOG("      a console interface (RPKG>), all the time keeping previously loaded RPKG files");
    LOG("      resident in rpkg-cli.exe's memory, speeding up successive commands immensely.");
    LOG("  Drag And Drop Options:");
    LOG("    - RPKG files can be dragged and dropped directly onto the rpkg-cli.exe file.");
    LOG("        This causes rpkg-cli.exe to automatically enter RPKG extraction mode and");
    LOG("        will fully extract all the hash files/resources from each RPKG dragged");
    LOG("        and dropped upon rpkg-cli.exe. It mimics (-extract_from_rpkg) in behaviour.");
    LOG("        One or more RPKG files can be dragged and dropped onto rpkg-cli.exe at a time.");
    LOG("    - rpkg-cli.exe command JSON files can be dragged and dropped onto the rpkg-cli.exe file.");
    LOG("        This causes rpkg-cli.exe to automatically enter rpkg-cli.exe command JSON mode and");
    LOG("        will import, parse, and run all the commands listed in the input JSON file.");
    LOG("        One or more JSON files can be dragged and dropped onto rpkg-cli.exe at a time." << std::endl);
    LOG("  Command Line Options:");
    LOG("    -compute_ioi_hash <string>");
    LOG("        Computes the IOI style truncated md5 hash/runtimeid from a string.");
    LOG("    -decrypt_packagedefinition_thumbs <path to file>");
    LOG("        Decrypts packagedefinitions.txt / thumbs.dat files.");
    LOG("    -encrypt_packagedefinition_thumbs <path to file>");
    LOG("        Encrypts packagedefinitions.txt / thumbs.dat files.");
    LOG("    -extract_all_hash_depends_from <path to folder containing RPKG files>");
    LOG("        Extracts all of the recursive hash depends, specified by -filter,");
    LOG("        of a given hash file/resource.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for dependency information.");
    LOG("    -extract_all_hash_depends_prim_models_from <path to folder containing RPKG files>");
    LOG("        Extracts all of the recursive PRIM Model(s) (GLB/TGA) hash depends,");
    LOG("        specified by -filter, of a given hash file/resource.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for dependency information.");
    LOG("    -extract_direct_hash_depends_from <path to folder containing RPKG files>");
    LOG("        Extracts the direct hash depends, specified by -filter,");
    LOG("        of a given hash file/resource.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for dependency information.");
    LOG("    -extract_direct_hash_depends_prim_models_from <path to folder containing RPKG files>");
    LOG("        Extracts all of the direct PRIM Model(s) (GLB/TGA) hash depends,");
    LOG("        specified by -filter, of a given hash file/resource.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for dependency information.");
    LOG("    -extract_from_rpkg <path to RPKG file>");
    LOG("        Extracts all hash linked files/resources from an RPKG file.");
    LOG("    -extract_gfxf_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources located in the GFXF files");
    LOG("        and unpacks them to GFX and if available DDS/TGA files from all");
    LOG("        the RPKG files in a given directory.");
    LOG("    -extract_ores_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources located in the ORES files");
    LOG("        by their full IOI path names from all the RPKG files in a given directory.");
    LOG("    -extract_wwem_to_ogg_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type WWEM to their");
    LOG("        full IOI internal Wwise file paths / names. It also converts");
    LOG("        the WWES (*.wem) files directly to *.ogg files for easy listening.");
    LOG("    -extract_wwes_to_ogg_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type WWES to their");
    LOG("        full IOI internal Wwise file paths / names. It also converts");
    LOG("        the WWES (*.wem) files directly to *.ogg files for easy listening.");
    LOG("    -extract_wwev_to_ogg_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type WWEV to their");
    LOG("        partial IOI internal Wwise file paths / names. It also converts");
    LOG("        the WWEV (*.wem) files directly to *.ogg files for easy listening.");
    LOG("    -extract_dlge_to_json_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type DLGE from");
    LOG("        all the RPKG files in a given directory and then decrypts");
    LOG("        them in memory and outputs / formats them as JSON files.");
    LOG("    -extract_locr_to_json_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type LOCR from");
    LOG("        all the RPKG files in a given directory and then decrypts");
    LOG("        them in memory and outputs / formats them as JSON files.");
    LOG("    -extract_prim_to_glb_from <path to RPKG file>");
    LOG("        Extracts hash linked files/resources of type PRIM specified by");
    LOG("        -filter from specified RPKG file and then converts them in memory");
    LOG("        and outputs / formats them as a single 3D glTF GLB file(s).");
    LOG("    -extract_prim_to_obj_from <path to RPKG file>");
    LOG("        Extracts hash linked files/resources of type PRIM specified by");
    LOG("        -filter from specified RPKG file and then converts them in memory");
    LOG("        and outputs / formats them as a single 3D OBJ file(s).");
    LOG("    -extract_rtlv_to_json_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type RTLV from");
    LOG("        all the RPKG files in a given directory and then decrypts");
    LOG("        them in memory and outputs / formats them as JSON files.");
    LOG("        and outputs / formats them as a single 3D OBJ file(s).");
    LOG("    -extract_prim_model_from <path to RPKG file>");
    LOG("        Extracts hash linked files/resources of type PRIM specified by");
    LOG("        -filter from specified RPKG file and then converts them in memory");
    LOG("        and outputs / formats them as a GLB/TGA file(s).");
    LOG("    -extract_all_prim_model_of_temp_from <path to RPKG file>");
    LOG("        Extracts hash linked files/resources of type PRIM which are hash");
    LOG("        depends of TEMP hash files specified by -filter from specified RPKG");
    LOG("        file and then converts them in memory and outputs / formats them");
    LOG("        as GLB/TGA file(s).");
    LOG("    -extract_all_text_from <path to folder containing RPKG files>");
    LOG("        Extracts all hash linked files/resources of type TEXT/TEXD from");
    LOG("        all the RPKG files in a given directory and then decrypts");
    LOG("        them in memory and outputs / formats them as TGA files.");
    LOG("    -extract_text_from <path to RPKG file>");
    LOG("        Extracts all hash linked files/resources of type TEXT/TEXD from");
    LOG("        all the RPKG files in a given directory and then decrypts");
    LOG("        them in memory and outputs / formats them as TGA files.");
    LOG("    -filter <hash filter>");
    LOG("        Filters hash linked files/resources by string filter.");
    LOG("        String filter can be a full hash value, partial hash value,");
    LOG("        the hash resource type, partial hash resource type, WWES or WWEV");
    LOG("        partial of full file/resource name, etc...");
    LOG("        Can accept multiple filters: -filter <filter1>,<filter2>,...");
    LOG("    -generate_rpkg_from <path to folder to generate rpkg from>");
    LOG("        Generates a RPKG file from hash file(s) in a given folder and all subfolders.");
    LOG("        The folder name is used for the filename of the generated RPKG file.");
    LOG("    -hash_depends <path to folder containing RPKG files>");
    LOG("        Lists the forward and reverse depends of a given hash file/resource.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for dependency information and lists the results.");
    LOG("    -hash_probe <path to folder containing RPKG files>");
    LOG("        Probes RPKG files for hash files/resources and displays key data points.");
    LOG("        Scans a directory, commonly Hitman's Runtime dir, and imports and");
    LOG("        scans all available RPKG files for the existence of the hash file/resource.");
    LOG("    -hex_search <hex string>");
    LOG("        Specifices the hex string to find within hash files/resources.");
    LOG("    -output_path <path to output folder>");
    LOG("        Specifies output folder path to use instead of the current directory.");
    LOG("    -rebuild_wwev_in <path to folders containing wem files>");
    LOG("        Rebuilds sets of individual Wwise .wem files that were previously");
    LOG("        extracted with (-extract_wwev_from). The folder specified by the");
    LOG("        argument can contain any number of sub folders, where each subfolder's");
    LOG("        name is linked to an individual WWEV that will be built from the *.wem");
    LOG("        files in that folder.");
    LOG("    -rebuild_gfxf_in <path to folders containing GFFX/(DDS/TGA) files>");
    LOG("        Rebuilds sets of GFX and if available DDS/TGA files that were previously");
    LOG("        extracted with (-extract_gfxf_from). The folder specified by the");
    LOG("        argument can contain any number of sub folders, where each subfolder's");
    LOG("        name is linked to an individual GFXF that will be built from");
    LOG("        the GFX and if available DDS/TGA files in that folder.");
    LOG("    -rebuild_dlge_from_json_from <path to folder containing JSON (DLGE) files>");
    LOG("        Rebuilds DLGE files/resources from JSON (DLGE) files that were previously");
    LOG("        extracted with (-extract_dlge_to_json_from).");
    LOG("    -rebuild_locr_from_json_from <path to folder containing JSON (LOCR) files>");
    LOG("        Rebuilds LOCR files/resources from JSON (LOCR) files that were previously");
    LOG("        extracted with (-extract_locr_to_json_from).");
    LOG("    -rebuild_prim_in <path to folder containing PRIM files>");
    LOG("        Rebuilds PRIM files/resources from GLB (PRIM) files that were previously");
    LOG("        extracted with (-extract_prim_to_glb_from).");
    LOG("    -rebuild_rtlv_from_json_from <path to folder containing JSON (RTLV) files>");
    LOG("        Rebuilds RTLV files/resources from JSON (RTLV) files that were previously");
    LOG("        extracted with (-extract_rtlv_to_json_from).");
    LOG("    -rebuild_text_in <path to folder containing TEXT/TEXD files>");
    LOG("        Rebuilds TEXT/TEXD files/resources from TGA (TEXT/TEXD) files that were previously");
    LOG("        extracted with (-extract_text_from or -extract_all_text_from).");
    LOG("    -regex_search <regex>");
    LOG("        Specifies the regex which is used to find within hash files/resources.");
    LOG("    -rpkg_command_json <path to rpkg command json file>");
    LOG("        Imports, parses, and runs all the commands listed in the input JSON file.");
    LOG("        See included rpkg_command_reference.JSON for complete JSON command descriptions.");
    LOG("        See included rpkg_command_JSON_examples\\*.JSON for some command JSON examples.");
    LOG("    -search_rpkg <path to RPKG file>");
    LOG("        Specifies RPKG file whose hash files/resources will to be searched through.");
    LOG("    -text_search <text string>");
    LOG("        Specifices the text string to find within hash files/resources.");
    LOG("  Examples:");
    LOG("    Computes the IOI style truncated md5 hash/runtimeid from a string:");
    LOG("        rpkg-cli.exe -compute_ioi_hash \"[assembly:/_PRO/Scenes/Missions/CoastalTown/Mission01.entity].pc_entitytemplate\"");
    LOG("    Decrypts packagedefinitions.txt / thumbs.dat files:");
    LOG("        rpkg-cli.exe -decrypt_packagedefinition_thumbs packagedefinition.txt");
    LOG("    Encrypts packagedefinitions.txt / thumbs.dat files:");
    LOG("        rpkg-cli.exe -encrypt_packagedefinition_thumbs packagedefinition.txt.decrypted");
    LOG("    Extracts all hash linked files/resources from an RPKG file:");
    LOG("        rpkg-cli.exe -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts all hash linked files/resources from an RPKG file to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts one hash linked files/resources from an RPKG file by hash filter:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts multiple hash linked files/resources from an RPKG file by hash filter:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE,00123456789ABCDE -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts all hash linked files/resources from an RPKG file by hash resource type filter:");
    LOG("        rpkg-cli.exe -filter ORES -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts all hash linked files/resources from an RPKG file by hash resource types ORES, REPO, and JSON:");
    LOG("        rpkg-cli.exe -filter ORES,REPO,JSON -extract_from_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Generates a RPKG file from hash file(s) in a given folder and all subfolders:");
    LOG("        rpkg-cli.exe -generate_rpkg_from chunk0patch1");
    LOG("    Extracts all of the recursive hash depends, specified by -filter, of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_all_hash_depends_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all of the recursive PRIM Model(s) (GLB/TGA) hash depends, specified by -filter, of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_all_hash_depends_prim_models_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all of the direct hash depends, specified by -filter, of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_direct_hash_depends_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all of the direct PRIM Model(s) (GLB/TGA) hash depends, specified by -filter, of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_direct_hash_depends_prim_models_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts PRIM (to 3D glTF GLB) hash linked files/resources from an RPKG file by hash filter:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_prim_to_glb_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts PRIM (to 3D OBJ) hash linked files/resources from an RPKG file by hash filter:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_prim_to_obj_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Extracts all hash linked files/resources located in the ORES files from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_ores_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources located in the ORES files from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_ores_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type DLGE from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_dlge_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type DLGE from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_dlge_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type LOCR from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_locr_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type LOCR from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_locr_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type RTLV from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_rtlv_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts and decrypts (to JSON) all hash linked files/resources of type RTLV from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_rtlv_to_json_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Rebuilds sets DLGE files from JSON files that were previously created with (-extract_dlge_to_json_from):");
    LOG("        rpkg-cli.exe -rebuild_dlge_from_json_from \"R:\\DLGE\"");
    LOG("    Rebuilds sets DLGE files from JSON files that were previously created with (-extract_dlge_to_json_from) to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -rebuild_dlge_from_json_from \"R:\\DLGE\"");
    LOG("    Rebuilds sets LOCR files from JSON files that were previously created with (-extract_locr_to_json_from):");
    LOG("        rpkg-cli.exe -rebuild_locr_from_json_from \"R:\\LOCR\"");
    LOG("    Rebuilds sets LOCR files from JSON files that were previously created with (-extract_locr_to_json_from):");
    LOG("        rpkg-cli.exe -rebuild_locr_from_json_from \"R:\\LOCR\"");
    LOG("    Rebuilds sets RTLV files from JSON files that were previously created with (-extract_rtlv_to_json_from) to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -rebuild_rtlv_from_json_from \"R:\\RTLV\"");
    LOG("    Rebuilds sets RTLV files from JSON files that were previously created with (-extract_rtlv_to_json_from) to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -rebuild_rtlv_from_json_from \"R:\\RTLV\"");
    LOG("    Extracts all hash linked files/resources of type WWEM from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_wwem_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources of type WWEM from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_wwem_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources of type WWES from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_wwes_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources of type WWES from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_wwes_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources of type WWEV from all the RPKG files in a given directory:");
    LOG("        rpkg-cli.exe -extract_wwev_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Extracts all hash linked files/resources of type WWEV from all the RPKG files in a given directory to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -extract_wwev_to_ogg_from \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Rebuilds sets of individual Wwise .wem files that were previously extracted with (-extract_wwev_from):");
    LOG("        rpkg-cli.exe -rebuild_wwev_in \"R:\\WWEV\"");
    LOG("    Rebuilds sets of individual Wwise .wem files that were previously extracted with (-extract_wwev_from) to an output folder:");
    LOG("        rpkg-cli.exe -output_path \"R:\\my\\output\\path\" -rebuild_wwev_in \"R:\\WWEV\"");
    LOG("    Lists and extracts the forward depends of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -extract_direct_hash_depends \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Lists and extracts the forward depends of two hash files/resources:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE,00123456789ABCDE -extract_direct_hash_depends \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Lists the forward and reverse depends of a given hash file/resource:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -hash_depends \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Lists the forward and reverse depends of two hash files/resources:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE,00123456789ABCDE -hash_depends \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Probes RPKG files for hash files/resources and displays key data points:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE -hash_probe \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Probes RPKG files for hash files/resources and displays key data points:");
    LOG("        rpkg-cli.exe -filter 00123456789ABCDE,00123456789ABCDE -hash_probe \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\"");
    LOG("    Search a RPKG file's hash files/resources by hex string:");
    LOG("        rpkg-cli.exe -hex_search 00112233445566 -search_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Search a RPKG file's hash files/resources by regex:");
    LOG("        rpkg-cli.exe -regex_search \"assembly:[\\w/_]+\" -search_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Search a RPKG file's hash files/resources by text string:");
    LOG("        rpkg-cli.exe -text_search assembly -search_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Search a RPKG file's hash files/resources by regex and filter by type ORES:");
    LOG("        rpkg-cli.exe -filter ORES -regex_search \"assembly:[\\w/_.]+\" -search_rpkg \"C:\\Program Files\\Epic Games\\HITMAN3\\Runtime\\chunk0.rpkg\"");
    LOG("    Imports, parses, and runs all the commands listed in the input JSON file:");
    LOG("      The JSON input below batch extracts from all the RPKGs in the Hitman 3 Runtime folder:");
    LOG("        rpkg-cli.exe -rpkg_command_json rpkg_command-batch_extract_chunk_rpkgs.JSON");
    std::system("pause");
}